// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2GYBg7dt0bjU1-mkU1psRy6WFUhiYEAg',
    appId: '1:113227962090:web:9b26baf4e320bdb650e993',
    messagingSenderId: '113227962090',
    projectId: 'flutterapp-bb5cd',
    authDomain: 'flutterapp-bb5cd.firebaseapp.com',
    storageBucket: 'flutterapp-bb5cd.appspot.com',
    measurementId: 'G-XMBB32N15K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-KrwHEVqIkduFHBWuQrN-alBsLfdpVI8',
    appId: '1:113227962090:android:9480562081a48f7950e993',
    messagingSenderId: '113227962090',
    projectId: 'flutterapp-bb5cd',
    storageBucket: 'flutterapp-bb5cd.appspot.com',
  );
}
